# contents

# metadata
site_name: 認識（とか）ドキュメント
docs_dir: docs
use_directory_urls: false
  
site_url: https://control.pages.robotech.t.u-tokyo.ac.jp/cognition-docs/
repo_url: https://git.robotech.t.u-tokyo.ac.jp/Control/cognition-docs

theme:
  name: material 
  language: ja
  palette:
    scheme: slate 
  features:
    - content.code.annotate
    - navigation.top
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
extra:
  search:
    language: 'jp'


