site_name: 認識（とか）ドキュメント
site_url: https://20niship.github.io/cognition-docs/
docs_dir: docs
use_directory_urls: true
theme:
  name: material 
  language: ja
  palette:
    scheme: slate 
  features:
    - content.code.annotate
    - navigation.top
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
extra:
  search:
    language: 'jp'


