name: Deploy mkdocs
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch 
        uses: actions/checkout@v3
      - name: setup python env
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: mkdocs build
        run: |
           mkdocs build --verbose --clean
      - name: mkdocs deploy
        run: mkdocs gh-deploy --force
